[package]
name = "warp_acp"
version = "0.1.0"
edition = "2021"
publish.workspace = true
license.workspace = true

[dependencies]
command = { workspace = true }
instant = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
